# for module compiling
import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

scr = os.path.join(cwd + '/../..', 'bsp/driver', 'SConscript')
if (os.path.exists(scr)):
    objs += SConscript(scr, variant_dir='bsp/driver', duplicate=0)

scr = os.path.join(cwd + '/../..', 'bsp/kendryte-sdk', 'SConscript')
if (os.path.exists(scr)):
    objs += SConscript(scr, variant_dir='bsp/kendryte-sdk', duplicate=0)

Return('objs')
